import {
  DEFAULT_ADMISSION_PREFIX,
  formatAdmissionNo,
  OWNER_LEGAL_DOCUMENTS,
} from '@academybee/contracts';

import type { Prisma, PrismaClient } from '../generated/prisma/client.js';
import { DEV_TENANTS } from './tenants.js';
import { DEV_USERS } from './users.js';

/**
 * Local/CI demo people and scheduling (C-09, C-37). demo-a gets a course, a batch taught by the
 * demo teacher on Mondays and Wednesdays, three students, and the demo parent linked to one of
 * them with a consent record — so the parent-activation guard never needs a bypass (C-37).
 * Every academy gets its onboarding state: finished unless it is still setting up. Fixed ids keep
 * re-runs idempotent. Class sessions are generated by the scheduling module (Phase 3 S5).
 */
const DEMO_A = {
  courseId: '01a10000-0000-7000-8000-00000000c001',
  batchId: '01a10000-0000-7000-8000-00000000b001',
  ownerTeacherId: '01a10000-0000-7000-8000-00000000e001',
  teacherId: '01a10000-0000-7000-8000-00000000e002',
  parentId: '01a10000-0000-7000-8000-00000000d001',
  rules: [
    { id: '01a10000-0000-7000-8000-00000000f001', weekday: 1 },
    { id: '01a10000-0000-7000-8000-00000000f003', weekday: 3 },
  ],
  students: [
    {
      id: '01a10000-0000-7000-8000-00000000a001',
      enrolmentId: '01a10000-0000-7000-8000-00000000a101',
      name: 'Aarav Sharma',
      grade: 'Grade 8',
    },
    {
      id: '01a10000-0000-7000-8000-00000000a002',
      enrolmentId: '01a10000-0000-7000-8000-00000000a102',
      name: 'Diya Iyer',
      grade: 'Grade 8',
    },
    {
      id: '01a10000-0000-7000-8000-00000000a003',
      enrolmentId: '01a10000-0000-7000-8000-00000000a103',
      name: 'Kabir Khan',
      grade: 'Grade 8',
    },
  ],
};

const userId = (email: string) => {
  const u = DEV_USERS.find((x) => x.email === email);
  if (!u) throw new Error(`Unknown demo user ${email}`);
  return u.id;
};

async function membershipId(tx: Prisma.TransactionClient, tenantId: string, email: string) {
  const m = await tx.membership.findFirstOrThrow({
    where: { tenantId, userId: userId(email) },
    select: { id: true },
  });
  return m.id;
}

export async function seedDevPeople(db: PrismaClient): Promise<number> {
  const today = new Date(new Date().toISOString().slice(0, 10));
  for (const t of DEV_TENANTS) {
    await db.$transaction(async (tx) => {
      await tx.$queryRaw`SELECT set_config('app.tenant_id', ${t.id}, true)`;
      const done = t.status !== 'SETUP';
      await tx.tenantOnboarding.upsert({
        where: { tenantId: t.id },
        create: {
          tenantId: t.id,
          currentStep: done ? 'ready' : 'profile',
          completedAt: done ? new Date() : null,
        },
        update: {},
      });
    });
  }

  // Owners of open demo academies have accepted the current legal documents (ADR-034), so
  // their pages don't stop at the legal step; the setting-up academy's owner hasn't (E2E walks it).
  for (const email of ['owner@demo-a.test', 'owner@demo-b.test']) {
    const user = userId(email);
    const tenant = DEV_TENANTS.find(
      (t) => t.slug === (email.includes('demo-a') ? 'demo-a' : 'demo-b'),
    )!;
    await db.$transaction(async (tx) => {
      await tx.$queryRaw`SELECT set_config('app.user_id', ${user}, true), set_config('app.tenant_id', ${tenant.id}, true)`;
      await tx.legalAcceptance.createMany({
        data: OWNER_LEGAL_DOCUMENTS.map((d) => ({
          // One stable id per document and owner (document id's first groups + its own last 4).
          id: `${d.id.slice(0, 19)}${d.id.slice(-4)}-${user.slice(-12)}`,
          userId: user,
          tenantId: tenant.id,
          documentId: d.id,
          locale: 'en-IN',
        })),
        skipDuplicates: true,
      });
    });
  }

  const a = DEV_TENANTS.find((t) => t.slug === 'demo-a');
  if (!a) throw new Error('demo-a missing');
  await db.$transaction(async (tx) => {
    await tx.$queryRaw`SELECT set_config('app.tenant_id', ${a.id}, true)`;
    const teachers = [
      { id: DEMO_A.ownerTeacherId, email: 'owner@demo-a.test', name: 'Demo Owner' },
      { id: DEMO_A.teacherId, email: 'teacher@demo-a.test', name: 'Demo Teacher' },
    ];
    for (const teacher of teachers)
      await tx.teacher.upsert({
        where: { id: teacher.id },
        create: {
          id: teacher.id,
          tenantId: a.id,
          branchId: a.branchId,
          membershipId: await membershipId(tx, a.id, teacher.email),
          fullName: teacher.name,
          email: teacher.email,
        },
        update: {},
      });

    await tx.course.upsert({
      where: { id: DEMO_A.courseId },
      create: { id: DEMO_A.courseId, tenantId: a.id, name: 'Mathematics' },
      update: {},
    });
    await tx.batch.upsert({
      where: { id: DEMO_A.batchId },
      create: {
        id: DEMO_A.batchId,
        tenantId: a.id,
        branchId: a.branchId,
        courseId: DEMO_A.courseId,
        name: 'Grade 8 — Evening',
        capacity: 20,
        startsOn: today,
      },
      update: {},
    });
    await tx.batchTeacher.createMany({
      data: [
        { tenantId: a.id, batchId: DEMO_A.batchId, teacherId: DEMO_A.teacherId, isPrimary: true },
      ],
      skipDuplicates: true,
    });
    // Mondays and Wednesdays, 17:00–18:00 in the academy's timezone.
    for (const rule of DEMO_A.rules)
      await tx.scheduleRule.upsert({
        where: { id: rule.id },
        create: {
          id: rule.id,
          tenantId: a.id,
          batchId: DEMO_A.batchId,
          teacherId: DEMO_A.teacherId,
          weekday: rule.weekday,
          startMinute: 17 * 60,
          endMinute: 18 * 60,
          effectiveFrom: today,
        },
        update: {},
      });

    for (const [i, s] of DEMO_A.students.entries()) {
      await tx.student.upsert({
        where: { id: s.id },
        create: {
          id: s.id,
          tenantId: a.id,
          branchId: a.branchId,
          admissionNo: formatAdmissionNo(DEFAULT_ADMISSION_PREFIX, i + 1),
          fullName: s.name,
          grade: s.grade,
          admissionDate: today,
          userId: i === 0 ? userId('student@demo-a.test') : null,
        },
        update: {},
      });
      const open = await tx.batchEnrolment.findFirst({
        where: { batchId: DEMO_A.batchId, studentId: s.id, endedOn: null },
        select: { id: true },
      });
      if (!open)
        await tx.batchEnrolment.create({
          data: {
            id: s.enrolmentId,
            tenantId: a.id,
            batchId: DEMO_A.batchId,
            studentId: s.id,
            startedOn: today,
          },
        });
    }
    await tx.tenantSequence.upsert({
      where: { tenantId_key: { tenantId: a.id, key: 'admission' } },
      create: { tenantId: a.id, key: 'admission', nextValue: DEMO_A.students.length + 1 },
      update: {},
    });

    // The demo parent: Aarav's mother, with consent recorded by the academy (C-37).
    const aarav = DEMO_A.students[0]!;
    await tx.parent.upsert({
      where: { id: DEMO_A.parentId },
      create: {
        id: DEMO_A.parentId,
        tenantId: a.id,
        fullName: 'Priya Sharma',
        phone: '+919800000101',
        whatsappCapable: true,
        email: 'parent@demo-a.test',
        userId: userId('parent@demo-a.test'),
      },
      update: {},
    });
    await tx.parentStudent.createMany({
      data: [
        {
          id: '01a10000-0000-7000-8000-00000000d101',
          tenantId: a.id,
          parentId: DEMO_A.parentId,
          studentId: aarav.id,
          relationship: 'MOTHER',
          isPrimaryContact: true,
          pickupAuthorised: true,
        },
      ],
      skipDuplicates: true,
    });
    await tx.consentRecord.createMany({
      data: [
        {
          id: '01a10000-0000-7000-8000-00000000d201',
          tenantId: a.id,
          parentId: DEMO_A.parentId,
          studentId: aarav.id,
          action: 'GRANT',
          purposes: ['service'],
          noticeVersion: 'demo',
          channel: 'ACADEMY_STAFF',
        },
      ],
      skipDuplicates: true,
    });
  });
  return DEMO_A.students.length;
}
