/**
 * Slugs that normal provisioning can never use (ARCHITECTURE §4.1, ADR-003). Only a
 * platform-owned tenant created by seed/CLI may use one (e.g. the sales demo `demo`, C-36).
 * Anything shorter than three characters is also refused (see `validateSlug`).
 */
export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  'www',
  'app',
  'my',
  'hub',
  'family',
  'parents',
  'api',
  'admin',
  'console',
  'platform',
  'auth',
  'login',
  'logout',
  'signup',
  'register',
  'account',
  'accounts',
  'mail',
  'email',
  'smtp',
  'static',
  'assets',
  'cdn',
  'media',
  'files',
  'img',
  'images',
  'docs',
  'help',
  'support',
  'status',
  'blog',
  'news',
  'billing',
  'pay',
  'payments',
  'invoice',
  'invoices',
  'dev',
  'staging',
  'stage',
  'test',
  'qa',
  'demo',
  'sandbox',
  'preview',
  'internal',
  'ops',
  'root',
  'system',
  'security',
  'academybee',
  'bee',
  'public',
  'private',
  'www2',
  'm',
  'mobile',
  'ftp',
  'ns1',
  'ns2',
  'localhost',
]);

export function isReservedSlug(slug: string): boolean {
  return slug.length < 3 || RESERVED_SLUGS.has(slug);
}
